
# tasks file for totti.plex
 - name: Install prerequesite
   apt: 
     pkg={{ item }}
     state=present
   with_items:
     - avahi-daemon
     - avahi-utils
     - bind9-host
     - dbus
     - geoip-database
     - libapparmor1
     - libavahi-client3
     - libavahi-common-data
     - libavahi-common3
     - libavahi-core7
     - libbind9-90
     - libdaemon0
     - libdns100
     - libgeoip1
     - libglib2.0-0
     - libglib2.0-data
     - libisc95
     - libisccc90
     - libisccfg90
     - liblwres90
     - libnss-mdns
     - libpam-systemd
     - libsystemd-daemon0
     - libsystemd-login0
     - libxml2
     - sgml-base
     - shared-mime-info
     - systemd-services
     - systemd-shim
     - xml-core

 - name: Download Plex pkg
   get_url:
     url={{ plex_url }}
     dest=/root/plex.deb

 - name: Install Plex
   apt:
     deb=/root/plex.deb

 - name: Change Plex Home dir
   replace:
     dest=/etc/passwd
     regexp="/var/lib/plexmediaserver"
     replace={{ plex_home_dir }}

 - name: Chown Plex Home Dir
   file:
     dest={{ plex_home_dir }}
     state=directory
     owner=plex
     mode=0755

# Start it
 - name: Ensure plex is running
   service: name=plexmediaserver state=started
